twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # C:\Sites\GarageParrot\GarageParrot\vendor\symfony\twig-bridge\Resources\views\Form

when@test:
    twig:
        strict_variables: true
